-- ATUALIZANDO O CAMPO DE UF 
select * from tb_cliente
UPDATE tb_cliente SET UF = 'SP' , cidade = 'SÃO PAULO' WHERE ID_CLIENTE = 2;

SELECT UF FROM tb_cliente;
SELECT * FROM tb_pedido;
alter table tb_pedido add dia int alter table tb_pedido add mes varchar(15) alter table tb_pedido add ano int

-- ATUALIZANDO OS NOVOS CAMPOS DE DATA CRIADOS 
UPDATE TB_PEDIDO SET DIA = DAY(DATA_COMPRA) , MES = CASE WHEN MONTH(DATA_COMPRA) = 1 THEN 'Janeiro' WHEN MONTH(DATA_COMPRA) = 2 THEN 'Fevereiro' WHEN MONTH(DATA_COMPRA) = 3 THEN 'Março' WHEN MONTH(DATA_COMPRA) = 4 THEN 'Abril' WHEN MONTH(DATA_COMPRA) = 5 THEN 'Maio' WHEN MONTH(DATA_COMPRA) = 6 THEN 'Junho' WHEN MONTH(DATA_COMPRA) = 7 THEN 'Julho' WHEN MONTH(DATA_COMPRA) = 8 THEN 'Agosto' WHEN MONTH(DATA_COMPRA) = 9 THEN 'Setembro' WHEN MONTH(DATA_COMPRA) = 10 THEN 'Outubro' WHEN MONTH(DATA_COMPRA) = 11 THEN 'Novembro' WHEN MONTH(DATA_COMPRA) = 12 THEN 'Dezembro' ELSE null END , ANO = YEAR(DATA_COMPRA) WHERE ID_CLIENTE = 2;

SELECT * FROM TB_PEDIDO;

-- ATUALIZANDO OS NOVOS CAMPOS DE DATA CRIADOS 
UPDATE TB_PEDIDO SET DIA = DAY(DATA_COMPRA) , MES = CASE WHEN MONTH(DATA_COMPRA) = 1 THEN 'Janeiro' WHEN MONTH(DATA_COMPRA) = 2 THEN 'Fevereiro' WHEN MONTH(DATA_COMPRA) = 3 THEN 'Março' WHEN MONTH(DATA_COMPRA) = 4 THEN 'Abril' WHEN MONTH(DATA_COMPRA) = 5 THEN 'Maio' WHEN MONTH(DATA_COMPRA) = 6 THEN 'Junho' WHEN MONTH(DATA_COMPRA) = 7 THEN 'Julho' WHEN MONTH(DATA_COMPRA) = 8 THEN 'Agosto' WHEN MONTH(DATA_COMPRA) = 9 THEN 'Setembro' WHEN MONTH(DATA_COMPRA) = 10 THEN 'Outubro' WHEN MONTH(DATA_COMPRA) = 11 THEN 'Novembro' WHEN MONTH(DATA_COMPRA) = 12 THEN 'Dezembro' ELSE null END , ANO = YEAR(DATA_COMPRA) WHERE ID_CLIENTE IN (1,3);