-- SELECIONANDO TODAS AS COLUNAS DA TABELA DE CLIENTES
SELECT * FROM tb_cliente;

-- SELECIONANDO APENAS COLUNAS ESPECIFICAS DA TABELA DE CLIENTES
SELECT cpf, nome, uf
FROM tb_cliente;

-- SELECIONANDO AS UF´S DISTINTAS DA TABELA DE CLIENTES
SELECT DISTINCT uf FROM tb_cliente;

-- CONTANDO A QUANTIDADE TOTAL DE REGISTROS DA TABELA DE CLIENTES
SELECT COUNT(*) FROM tb_cliente

-- CONTANDO A QUANTIDADE TOTAL DE REGISTROS COM CPF´S DISTINTOS DA TABELA DE CLIENTES
SELECT COUNT(DISTINCT cpf) FROM tb_cliente;

-- SELECIONANDO APENAS OS 2 PRIMEIROS DA TABELA DE CLIENTES
SELECT TOP 2 * FROM tb_cliente;

-- SELECIONANDO E ORDENANDO OS REGISTROS POR ORDEM ALFABÉTICA POR NOME DA TABELA DE CLIENTES
SELECT * FROM tb_cliente ORDER BY nome;

-- SELECIONANDO E ORDENANDO OS REGISTROS EM ORDEM DESCRECENTE POR DATA DE NASCIMENTO DA TABELA DE CLIENTES
SELECT * FROM tb_cliente ORDER BY data_nascimento DESC;

-- SELECIONANDO E ORDENANDO OS REGISTROS ALEATÓRIAMENTE DA TABELA DE CLIENTES
SELECT * FROM tb_cliente ORDER BY NEWID();