-- USANDO O CASE WHEN PARA TRATAMENTO DO MÊS
SELECT DATA_COMPRA , DAY(DATA_COMPRA) AS DIA , MONTH(DATA_COMPRA) AS MES_NUMERO , CASE WHEN MONTH(DATA_COMPRA) = 1 THEN 'Janeiro' WHEN MONTH(DATA_COMPRA) = 2 THEN 'Fevereiro' WHEN MONTH(DATA_COMPRA) = 3 THEN 'Março' WHEN MONTH(DATA_COMPRA) = 4 THEN 'Abril' WHEN MONTH(DATA_COMPRA) = 5 THEN 'Maio' WHEN MONTH(DATA_COMPRA) = 6 THEN 'Junho' WHEN MONTH(DATA_COMPRA) = 7 THEN 'Julho' WHEN MONTH(DATA_COMPRA) = 8 THEN 'Agosto' WHEN MONTH(DATA_COMPRA) = 9 THEN 'Setembro' WHEN MONTH(DATA_COMPRA) = 10 THEN 'Outubro' WHEN MONTH(DATA_COMPRA) = 11 THEN 'Novembro' WHEN MONTH(DATA_COMPRA) = 12 THEN 'Dezembro' ELSE null END AS MES_TRATADO , YEAR(DATA_COMPRA) AS ANO FROM TB_PEDIDO WHERE YEAR(DATA_COMPRA) = 2022;

-- USANDO O CASE WHEN PARA TRATAMENTO DO GENERO 
SELECT GENERO , CASE WHEN GENERO = 'F' THEN 'Feminino' WHEN GENERO = 'M' THEN 'Masculino' ELSE 'Indefinido' END AS GENERO_TRATADO FROM tb_CLIENTE;

-- USANDO O IF PARA TRATAMENTO DO GENERO
SELECT GENERO , IIF(GENERO = 'F','Feminino','Masculino') FROM tb_CLIENTE;