-- INSERINDO DADOS NA TABELA DE CLIENTES
INSERT INTO tb_cliente ( CPF ,NOME ,DATA_NASCIMENTO ,GENERO ,ENDERECO ,BAIRRO ,CIDADE ,UF ,CEP ) VALUES (1111,'CAMILA','19880209','F','RUA: MONTE VERDE,100','VILA IPIRANGA','MOGI DAS CRUZES','SP','8735510');

INSERT INTO tb_cliente VALUES (2222,'KIKO','19881125','F','RUA: SUZANO, 500', 'COPACABANA', 'RIO DE JANEIRO','RJ','8778510');

INSERT INTO tb_cliente ( CPF ,NOME ,DATA_NASCIMENTO ) VALUES (3333,'SEU MADRUGA','20000508');

INSERT INTO tb_cliente ( CPF ,NOME ,DATA_NASCIMENTO ,GENERO ,ENDERECO ,BAIRRO ,CIDADE ,UF ,CEP ) VALUES (1111,'CHIQUINHA','19880209','F','RUA: MONTE VERDE,100','VILA IPIRANGA','MOGI DAS CRUZES','SP','8735510');

INSERINDO DADOS NA TABELA DE EMAIL
INSERT INTO tb_EMAIL ( ID_CLIENTE ,EMAIL ,SCORE ) VALUES (1,'CHIQUINHA@GMAIL.COM',1);

INSERT INTO tb_EMAIL ( ID_CLIENTE ,EMAIL ,SCORE ) VALUES (2,'KIKO@GMAIL.COM',1);

INSERT INTO tb_EMAIL ( ID_CLIENTE ,EMAIL ,SCORE ) VALUES (3,'SEU_MADRUGA@GMAIL.COM',1);

INSERT INTO tb_EMAIL ( ID_CLIENTE ,EMAIL ,SCORE ) VALUES (3,'SEU_MADRUGA_2@GMAIL.COM',2);

INSERINDO DADOS NA TABELA DE TELEFONE
INSERT INTO tb_telefone (ID_CLIENTE ,DDD ,TELEFONE, TIPO_TELEFONE, SCORE ) VALUES (1,11,985903841,'C',1);

INSERT INTO tb_telefone (ID_CLIENTE ,DDD ,TELEFONE, TIPO_TELEFONE, SCORE ) VALUES (1,11,985697854,'C',2);

INSERT INTO tb_telefone (ID_CLIENTE ,DDD ,TELEFONE, TIPO_TELEFONE, SCORE ) VALUES (2,11,985429623,'C',1);

INSERT INTO tb_telefone (ID_CLIENTE ,DDD ,TELEFONE, TIPO_TELEFONE, SCORE ) VALUES (2,11,987459652,'C',2);

INSERT INTO tb_telefone (ID_CLIENTE ,DDD ,TELEFONE, TIPO_TELEFONE, SCORE ) VALUES (3,11,945896328,'C',1);

-- INSERINDO DADOS NA TABELA DE PRODUTOS
INSERT INTO tb_produto (DESC_PRODUTO ,VALOR_PRODUTO, QTD_ESTOQUE) VALUES ('Bola Quadrada',90,12452);

INSERT INTO tb_produto (DESC_PRODUTO ,VALOR_PRODUTO, QTD_ESTOQUE) VALUES ('Maquina Fotografica',120,1245);

INSERT INTO tb_produto (DESC_PRODUTO, VALOR_PRODUTO, QTD_ESTOQUE) VALUES ('Sanduiche de Presunto',60,4574);

INSERT INTO tb_produto (DESC_PRODUTO ,VALOR_PRODUTO, QTD_ESTOQUE) VALUES ('Chinforinfola',40,32569);

INSERINDO DADOS NA TABELA DE PEDIDOS
INSERT INTO tb_pedido (ID_CLIENTE ,DATA_COMPRA ,NUM_NOTA_FISCAL, SERIE_NOTA_FISCAL, VALOR_TOTAL, QTD_TOTAL) VALUES (1,'20220209','aaa1254',111,207,2);

INSERT INTO tb_pedido (ID_CLIENTE ,DATA_COMPRA ,NUM_NOTA_FISCAL, SERIE_NOTA_FISCAL, VALOR_TOTAL, QTD_TOTAL) VALUES (1,'20221213','aaa1255',238,133,3);

INSERT INTO tb_pedido (ID_CLIENTE ,DATA_COMPRA ,NUM_NOTA_FISCAL, SERIE_NOTA_FISCAL, VALOR_TOTAL, QTD_TOTAL) VALUES (1,'20221215','aaa1256',122,528,5);

INSERT INTO tb_pedido (ID_CLIENTE ,DATA_COMPRA ,NUM_NOTA_FISCAL, SERIE_NOTA_FISCAL, VALOR_TOTAL, QTD_TOTAL) VALUES (1,'20220320','aaa1257',145,94,2);

INSERT INTO tb_pedido (ID_CLIENTE ,DATA_COMPRA ,NUM_NOTA_FISCAL, SERIE_NOTA_FISCAL, VALOR_TOTAL, QTD_TOTAL) VALUES (1,'20220320','aaa1258',258,206,2);

INSERT INTO tb_pedido (ID_CLIENTE ,DATA_COMPRA ,NUM_NOTA_FISCAL, SERIE_NOTA_FISCAL, VALOR_TOTAL, QTD_TOTAL) VALUES (2,'20220926','aaa1259',963,194,4);

INSERT INTO tb_pedido (ID_CLIENTE ,DATA_COMPRA ,NUM_NOTA_FISCAL, SERIE_NOTA_FISCAL, VALOR_TOTAL, QTD_TOTAL) VALUES (2,'20220712','bnb4886',147,289,3);

INSERT INTO tb_pedido (ID_CLIENTE ,DATA_COMPRA ,NUM_NOTA_FISCAL, SERIE_NOTA_FISCAL, VALOR_TOTAL, QTD_TOTAL) VALUES (2,'20220715','bnb4887',856,95,2);

INSERT INTO tb_pedido (ID_CLIENTE ,DATA_COMPRA ,NUM_NOTA_FISCAL, SERIE_NOTA_FISCAL, VALOR_TOTAL, QTD_TOTAL) VALUES (3,'20220701','bnb4888',321,408,4);

INSERT INTO tb_pedido (ID_CLIENTE ,DATA_COMPRA ,NUM_NOTA_FISCAL, SERIE_NOTA_FISCAL, VALOR_TOTAL, QTD_TOTAL) VALUES (3,'20220403','bnb4889',788,214,4);

INSERT INTO tb_pedido (ID_CLIENTE ,DATA_COMPRA ,NUM_NOTA_FISCAL, SERIE_NOTA_FISCAL, VALOR_TOTAL, QTD_TOTAL) VALUES (3,'20220415','cfd7785',741,207,2);

INSERT INTO tb_pedido (ID_CLIENTE ,DATA_COMPRA ,NUM_NOTA_FISCAL, SERIE_NOTA_FISCAL, VALOR_TOTAL, QTD_TOTAL) VALUES (3,'20220715','cfd7786',125,133,3);

INSERT INTO tb_pedido (ID_CLIENTE ,DATA_COMPRA ,NUM_NOTA_FISCAL, SERIE_NOTA_FISCAL, VALOR_TOTAL, QTD_TOTAL) VALUES (3,'20220218','cfd7787',963,410,4);

INSERT INTO tb_pedido (ID_CLIENTE ,DATA_COMPRA ,NUM_NOTA_FISCAL, SERIE_NOTA_FISCAL, VALOR_TOTAL, QTD_TOTAL) VALUES (3,'20221110','cfd7788',125,94,2);

INSERINDO DADOS NA TABELA DE itens
INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (1,1,88,2,1);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (1,2,119,1,1);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (2,3,55,5,1);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (2,4,39,1,2);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (3,1,87,3,2);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (3,2,118,2,3);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (4,3,59,1,1);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (4,4,35,5,1);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (5,1,89,1,1);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (5,2,117,3,1);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (6,3,58,2,2);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (6,4,39,1,2);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (7,1,85,5,2);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (7,2,119,1,1);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (8,3,57,3,1);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (8,4,38,2,1);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (9,1,89,1,2);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (9,2,115,5,2);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (10,3,59,1,3);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (10,4,37,3,1);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (11,1,88,2,1);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (11,2,119,1,1);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (12,3,55,5,1);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (12,4,39,1,2);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (13,1,87,3,2);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (13,2,118,2,2);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (14,3,59,1,1);

INSERT INTO tb_item_pedido (ID_PEDIDO, ID_PRODUTO, VALOR_ITEM, VALOR_DESCONTO, QTD_ITEM) VALUES (14,4,35,5,1);